# Generated by Django 5.2.13 on 2026-07-09 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anonymous_sessions', '0003_anonymoussession_identity_mode'),
        ('psychologists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PsychologistAvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_booked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='psychologists.psychologistprofile')),
            ],
            options={
                'ordering': ('date', 'start_time'),
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('appointment_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('notes', models.TextField(blank=True)),
                ('identity_mode', models.CharField(choices=[('anonymous', 'Anonymous'), ('known', 'Known')], default='anonymous', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='psychologists.psychologistprofile')),
                ('session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment', to='anonymous_sessions.anonymoussession')),
                ('availability_slot', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='appointment', to='appointments.psychologistavailabilityslot')),
            ],
            options={
                'ordering': ('appointment_date', 'start_time'),
            },
        ),
        migrations.AddConstraint(
            model_name='psychologistavailabilityslot',
            constraint=models.UniqueConstraint(fields=('psychologist', 'date', 'start_time', 'end_time'), name='unique_psychologist_slot_time'),
        ),
    ]
