# Generated by Django 5.2.13 on 2026-06-10 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonymous_sessions', '0001_initial'),
        ('psychologists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anonymoussession',
            name='is_active',
        ),
        migrations.AddField(
            model_name='anonymoussession',
            name='anonymous_alias',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='anonymoussession',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anonymous_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='anonymoussession',
            name='psychologist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anonymous_sessions', to='psychologists.psychologistprofile'),
        ),
        migrations.AddField(
            model_name='anonymoussession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('ended', 'Ended')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='anonymoussession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
