# Generated by Django 5.2.13 on 2026-06-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonymous_sessions', '0002_remove_anonymoussession_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymoussession',
            name='identity_mode',
            field=models.CharField(choices=[('anonymous', 'Anonymous'), ('known', 'Known')], default='anonymous', max_length=20),
        ),
    ]
